#! /bin/sh

set -e

# submit number
n=95754150


i=0
while test -e /home/icfp-run-$i
do
  i=`expr $i + 1`
done
u=icfp-run-$i
sudo adduser --disabled-password --gecos icfp $u
echo

cd /home/$u

run="sudo -u $u sh -c"

echo extracting...
$run 'tar xf -'
$run "tar xf icfp-$n.tgz"
echo

echo running install...
$run './install'
echo

echo running run_lifter...
$run 'cat *.map | ./ruby/bin/ruby -I ruby/lib/ruby/1.9.1 -I ruby/lib/ruby/1.9.1/i686-linux /home/icfp-run/.ssh/run_lifter'

echo all done.
